config/routes.rb
LexiqueCuisine::Application.routes.draw do
  get 'alphabetique' => 'public#alpha', :as => :alpha
  post 'recherche'    => 'lexiques#index', :as => :search

  resources :categories

  resources :comments

  resources :lexiques

  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get "public/index"
  get ":permalink" => 'categories#show', :as => :category_permalink
  get "definitions/:permalink" => 'lexiques#show', :as => :lexique_permalink

  root :to => 'public#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lexique
  attr_accessible :content, :validated_at
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= simple_form_for @comment, :html => { :class => 'form-horizontal' } do |f|
  = f.input :user_id
  = f.input :validated_at
  = f.input :content
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), comments_path, :class => 'btn'

app/views/comments/edit.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/index.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:validated_at)
      %th= model_class.human_attribute_name(:content)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to comment.id, comment_path(comment)
        %td= comment.user_id
        %td= comment.validated_at
        %td= comment.content
        %td=l comment.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(comment), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(comment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_comment_path, :class => 'btn btn-primary'

app/views/comments/new.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/show.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @comment.user_id
%p
  %strong= model_class.human_attribute_name(:validated_at) + ':'
  %br
  = @comment.validated_at
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @comment.content

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), comments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(@comment), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(@comment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'