config/routes.rb
LexiqueCuisine::Application.routes.draw do
  get 'alphabetique' => 'public#alpha', :as => :alpha
  post 'recherche'    => 'lexiques#index', :as => :search

  resources :categories

  resources :comments

  resources :lexiques

  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get "public/index"
  get ":permalink" => 'categories#show', :as => :category_permalink
  get "definitions/:permalink" => 'lexiques#show', :as => :lexique_permalink

  root :to => 'public#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Paperclip::Glue
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :image, :meta_description, :name, :title, :description, :permalink
  has_many :lexiques

  validates :permalink, :uniqueness => true, :presence => true
  validates :name, :uniqueness => true, :presence => true
  validates :title, :uniqueness => true, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.where(:permalink => params[:permalink])
    redirect_to root_url if !@category or !@category.first

    @category = @category.first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name, :input_html => {:class => 'input-xxlarge'}
  = f.input :permalink, :input_html => {:class => 'input-xxlarge'}
  = f.input :meta_description, :input_html => {:class => 'input-xxlarge'}
  = f.input :title, :input_html => {:class => 'input-xxlarge'}
  = f.input :description, :input_html =>  { :class => 'input-xxlarge wysihtml5', :rows => 9 }
  = f.input :image
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn'

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/categories/index.html.haml
- content_for :description,'Liste des categories'
- content_for :title, 'Liste des categories'
- content_for :sidebar do
  .span3
    .well.sidebar-nav
      %div
        = render :partial => 'layouts/google300'
      %div
        = render :partial => 'layouts/google300'
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
  %p
    = render :partial => 'layouts/googletheme'

  .row-fluid
    %ul.thumbnails
      - @categories.each do |category|
        %li.span4
          .thumbnail
            = link_to image_tag(category.image.url(:medium)), category_permalink_path(:permalink => category.permalink) if category.image?
            .caption
              %h3
                = link_to category.name, category_permalink_path(:permalink => category.permalink)
              %p
                = category.description
              - if current_user and current_user.is_admin
                %p
                  = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-primary'
                  = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary' if current_user and current_user.is_admin

app/views/categories/new.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/categories/show.html.haml
- content_for :description, @category.meta_description
- content_for :title, @category.title
- content_for :sidebar do
  .span3
    .well.sidebar-nav
      %div
        = render :partial => 'layouts/google300'
      %div
        = render :partial => 'layouts/google300'

- model_class = Category
.page-header
  %h1=@category.name
  %p
    = raw @category.description
  %p
    = render :partial => 'layouts/googletheme'
.row-fluid
  %ul.thumbnails
    - @category.lexiques.published.each do |lexique|
      %li.span4
        .thumbnail
          = link_to image_tag(lexique.image.url(:medium)), lexique_permalink_path(:permalink => lexique.permalink) if lexique.image?
          .caption
            %h3
              = link_to lexique.name, lexique_permalink_path(:permalink => lexique.permalink)
            %p
              = lexique.short_description
            - if current_user and current_user.is_admin
              %p
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_lexique_path(lexique), :class => 'btn btn-primary'
                = link_to t('.destroy', :default => t("helpers.links.destroy")), lexique_path(lexique), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'