config/routes.rb
LexiqueCuisine::Application.routes.draw do
  get 'alphabetique' => 'public#alpha', :as => :alpha
  post 'recherche'    => 'lexiques#index', :as => :search

  resources :categories

  resources :comments

  resources :lexiques

  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get "public/index"
  get ":permalink" => 'categories#show', :as => :category_permalink
  get "definitions/:permalink" => 'lexiques#show', :as => :lexique_permalink

  root :to => 'public#index'
end

app/models/lexique.rb
class Lexique < ActiveRecord::Base
  include Paperclip::Glue
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :permalink, :image, :description, :keywords, :meta_description, :name, :published_at, :short_description, :title, :published_at, :family, :synonyme, :category_id, :courant, :home_view, :first_letter
  scope :published, lambda { where(['ISNULL(published_at) or published_at<=?', Date.today]).order('name asc') }
  belongs_to :category
  has_many :comments


  validates :permalink, :uniqueness => true, :presence => true
  validates :name, :uniqueness => true, :presence => true
  validates :title, :uniqueness => true, :presence => true
  validates :first_letter, :presence => true
end

app/controllers/lexiques_controller.rb
class LexiquesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  # GET /lexiques
  # GET /lexiques.json
  def index
    if params[:lexique] and params[:lexique][:name]
      @lexiques = Lexique.where("name LIKE '%#{params[:lexique][:name]}%'").published
    elsif current_user and current_user.is_admin
      @lexiques = Lexique.all
    end

    redirect_to root_url if !@lexiques

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lexiques }
    end
  end

  # GET /lexiques/1
  # GET /lexiques/1.json
  def show
    @lexique = Lexique.where(:permalink => params[:permalink])
    redirect_to root_url if !@lexique or !@lexique.first

    @lexique = @lexique.first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lexique }
    end
  end

  # GET /lexiques/new
  # GET /lexiques/new.json
  def new
    @lexique = Lexique.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lexique }
    end
  end

  # GET /lexiques/1/edit
  def edit
    @lexique = Lexique.find(params[:id])
  end

  # POST /lexiques
  # POST /lexiques.json
  def create
    @lexique = Lexique.new(params[:lexique])

    respond_to do |format|
      if @lexique.save
        format.html { redirect_to lexiques_path, notice: 'Lexique was successfully created.' }
        format.json { render json: @lexique, status: :created, location: @lexique }
      else
        format.html { render action: "new" }
        format.json { render json: @lexique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lexiques/1
  # PUT /lexiques/1.json
  def update
    @lexique = Lexique.find(params[:id])

    respond_to do |format|
      if @lexique.update_attributes(params[:lexique])
        format.html { redirect_to lexiques_path, notice: 'Lexique was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lexique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lexiques/1
  # DELETE /lexiques/1.json
  def destroy
    @lexique = Lexique.find(params[:id])
    @lexique.destroy

    respond_to do |format|
      format.html { redirect_to lexiques_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lexiques_helper.rb
module LexiquesHelper
end

app/views/lexiques/_form.html.haml
= simple_form_for @lexique, :html => { :class => 'form-horizontal' } do |f|
  - @lexique.published_at = @lexique.published_at.strftime('%F') if @lexique.published_at
  = f.association :category
  = f.input :first_letter, :input_html => {:class => 'input-large'}
  = f.input :title, :input_html => {:class => 'input-xxlarge'}
  = f.input :name, :input_html => {:class => 'input-xxlarge'}
  = f.input :permalink, :input_html => {:class => 'input-xxlarge'}
  = f.input :short_description, :input_html =>  { :class => 'input-xxlarge', :rows => 9 }
  = f.input :meta_description, :input_html => {:class => 'input-xxlarge'}
  = f.input :description, :input_html =>  { :class => 'input-xxlarge wysihtml5', :rows => 9 }
  = f.input :keywords, :input_html => {:class => 'input-xxlarge', :rows => 9}
  = f.input :published_at, :input_html => {:class => 'datepicker', :'data-behaviour' => 'datepicker'}, :as => :string
  = f.input :family, :input_html => {:class => 'input-xxlarge', :rows => 9}
  = f.input :synonyme, :input_html => {:class => 'input-xxlarge', :rows => 9}

  = f.input :courant
  = f.input :image, :label => "Image"
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), lexiques_path, :class => 'btn'

app/views/lexiques/edit.html.haml
- model_class = Lexique
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/lexiques/index.html.haml
- model_class = Lexique
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
.row-fluid
  %ul.thumbnails
    - @lexiques.each do |lexique|
      %li.span4
        .thumbnail
          = link_to image_tag(lexique.image.url(:medium)), lexique_permalink_path(:permalink => lexique.permalink) if lexique.image?
          .caption
            %h3
              = link_to lexique.name, lexique_permalink_path(:permalink => lexique.permalink)
            %p
              = lexique.short_description
            - if current_user and current_user.is_admin
              %p
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_lexique_path(lexique), :class => 'btn btn-primary'
                = link_to t('.destroy', :default => t("helpers.links.destroy")), lexique_path(lexique), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
= link_to t('.new', :default => t("helpers.links.new")), new_lexique_path, :class => 'btn btn-primary' if current_user and current_user.is_admin

app/views/lexiques/new.html.haml
- model_class = Lexique
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/lexiques/show.html.haml
- content_for :description, @lexique.meta_description
- content_for :title, @lexique.title
- content_for :sidebar do
  .span3
    .well.sidebar-nav
      %div
        = render :partial => 'layouts/google300'
      %div
        = render :partial => 'layouts/google300'

- model_class = Lexique

.page-header
  %h1
    =@lexique.name
  - if @lexique.category
    %p
      %strong= model_class.human_attribute_name(:category_id) + ':'
      = link_to @lexique.category.name, category_permalink_path(:permalink => @lexique.category.permalink)
%p
  = render :partial => 'layouts/googletheme'
%p
  = raw @lexique.description
  = image_tag @lexique.image.url(:medium), :style => 'float:right' if @lexique.image?
.clearfix
.row-fluid
  - if @lexique.family
    .span6
      %p
        %strong
          Autre(s) mot(s) de la même famille
        %br
        = @lexique.family
  - if @lexique.synonyme
    .span6
      %p
        %strong
          Synonyme
        %br
        = @lexique.synonyme