config/routes.rb
LexiqueCuisine::Application.routes.draw do
  get 'alphabetique' => 'public#alpha', :as => :alpha
  post 'recherche'    => 'lexiques#index', :as => :search

  resources :categories

  resources :comments

  resources :lexiques

  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}

  get "public/index"
  get ":permalink" => 'categories#show', :as => :category_permalink
  get "definitions/:permalink" => 'lexiques#show', :as => :lexique_permalink

  root :to => 'public#index'
end

app/views/layouts/_analytic.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-6417778-21']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/_google300.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2598568117636697";
/* lexique-300 */
google_ad_slot = "6146644778";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/_googletheme.html.erb
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2598568117636697";
/* lexique-theme */
google_ad_slot = "9100111176";
google_ad_width = 468;
google_ad_height = 15;
//-->
</script>
<script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta{:content => yield(:description), :name => "description"}/
    - if yield(:og_image)!=''
      %meta{:content => yield(:og_url), :property => 'og:url'}
      %meta{:content => yield(:og_name), :property => 'og:site_name'}
      %meta{:content => yield(:og_image), :property => 'og:image'}
    %title= content_for?(:title) ? yield(:title) : "Lexique de Cuisine"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link{:href => "http://fonts.googleapis.com/css?family=Boogaloo", :rel => "stylesheet", :type => "text/css"}/
    = render :partial => 'layouts/analytic'


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'LexiqueCuisine', root_url, :class => 'brand'
          .container.nav-collapse
            %ul.nav
              %li{:class => (request.fullpath==categories_path ? 'active' : '')}
                = link_to "Categories", categories_path
              %li{:class => (request.fullpath==alpha_path ? 'active' : '')}
                = link_to "A à Z", alpha_path
              %li{:class => (request.fullpath==lexiques_path ? 'active' : '')}
                = link_to "Lexique", lexiques_path if current_user and current_user.is_admin
            - if @lexique
              = simple_form_for @lexique, :html => { :class => 'navbar-search pull-left form-search' }, :method => :post, :url => search_path do |f|
                .input-append
                  = f.text_field :name, :class => 'search-query span2', :value => '', :placeholder => (@lexique ? @lexique.name : '')
                  %button.btn{:type => "submit"} Rechercher
            %ul.nav.pull-right
              %li
                = link_to "Sign in", new_session_path('user') if !current_user
              %li= link_to "Logout", destroy_user_session_path, :method => :delete if current_user
    .container-fluid{:class => (root_path==request.fullpath ? 'slider-wrapper' : '')}
      .row-fluid
        - if content_for?(:sidebar)
          .span9
            = yield
          = yield(:sidebar)
        - else
          .span12
            = yield
          = yield(:sidebar)
    %footer.footer
      .container-fluid
        %p &copy; Miseajour.net 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"